UBUNTU: ubuntu: aufs -- Temporarily disable due to build failure
ubuntu/aufs/f_op.c: In function 'aufs_fsync_nondir':
ubuntu/aufs/f_op.c:785:3: error: too few arguments to function 'h_file->f_op->fsync'
ubuntu/aufs/dir.c: In function 'au_do_fsync_dir_no_file':
ubuntu/aufs/dir.c:299:4: error: too few arguments to function 'h_inode->i_fop->fsync'

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>